---
title: "Task 1"
author: "Sachiko Lamen"
date: "3/1/2022"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include= FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(here)
library(broom)
library(sf) # vector, spatial data 
library(tmap) # create cool thematic maps easily
library(janitor)
library(spatstat)
library(maptools)
library(raster)
library(tidyverse)
```

```{r}
# Read in data
oil_spill_sf <- read_sf(here("data", "oil_spill_shape", "Oil_Spill_Incident_Tracking_[ds394].shp")) %>%
  select(date = DATEOFINCI, county = LOCALECOUN)

ca_sf <- read_sf(here("data", "ca_counties", "CA_Counties_TIGER2016.shp")) %>%
  clean_names() %>%
  select(county_name = name, land_area = aland)

# View CRS info
oil_spill_sf %>% st_crs()
ca_sf %>% st_crs()
# Looks like they are the same! Yay!
```

```{r, include = TRUE}
# Interactive exploratory plot using tmap
tmap_mode(mode = 'view')
tm_shape(ca_sf) +
  tm_borders(col = 'black') +
  tm_shape(oil_spill_sf) +
  tm_dots()
```

### Wrangle to find oil spill incidents per county

```{r}
# Join oil spill and california counties data sets/geometry
ca_oil_sf <- ca_sf %>%
  st_join(oil_spill_sf)

# Count number of oil spills per county (exclude counties that have NA values)
oil_counts_sf <- ca_oil_sf %>%
  group_by(county_name) %>%
  summarize(n_records = sum(!is.na(county_name))) 
```

```{r}
# Choropleth Map
ggplot(data = oil_counts_sf) +
  geom_sf(aes(fill = n_records), color = 'white', size = 0.1) +
  scale_fill_gradientn(colors = c('lightgrey', 'darkorchid', 'navyblue')) +
  theme_void() +
  labs(fill = "Number of Oil Spills",
       title = "CA Oil Spills Per County 2008")

# Cool interactive choropleth map using tmap
tmap_mode(mode = 'view')
tm_shape(oil_counts_sf) +
  tm_borders(col = 'black') +
  tm_fill('n_records', palette = 'BuPu') 
```

```{r}
oil_sp <- as(oil_spill_sf, 'Spatial') # Convert to object 'Spatial'
oil_ppp <- as(oil_sp, 'ppp') # Convert to spatial point pattern

ca_sp <- as(ca_sf, 'Spatial') # Convert to object 'Spatial'
ca_win <- as(ca_sp, 'owin') # this window will exclude marine oil spills, but there is still enough data to perform G Function analysis without these observations

# Combine as a point pattern object (points + window):
oil_full <- ppp(oil_ppp$x, oil_ppp$y, window = ca_win) 

plot(oil_full) # Illegal point (outside window) shows up as the plus sign
```

## NEAREST NEIGHBOR (G FUNCTION)

```{r}
r_vec <- seq(0, 10000, by = 100) # make vector containing values from 0 - 10,000 that will be used to calculate G(r)

gfunction <- envelope(oil_full, fun = Gest, r = r_vec, nsim = 20, nrank = 2) # Calculate the actual and theoretical G(r) values, using 20 simulations of CRS for the "theoretical" outcome (the processing time is very low so fewer simulations will run faster)

gfunction_long <- gfunction %>%
  as.data.frame() %>%
  pivot_longer(cols = obs:hi, names_to = 'model', values_to = 'g_val')

ggplot(data = gfunction_long, aes(x = r, y = g_val, group = model)) +
  geom_line(aes(color = model))
```

This confirms clustering - our data has a greater proportion of events with nearest neighbor at *smaller distances* compared to a theoretical CSR scenario.













